config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

# get 'lists/new', to: 'lists#new'
# post '/lists', to: 'lists#create'
# get 'lists', to: 'lists#index'
# get 'lists/:id', to: 'lists#show', as: :restaurant

  root to: 'lists#index'

  resources :lists, only: [:new, :create, :index, :show] do
    resources :bookmarks, only: [:new, :create]
  end
  resources :bookmarks, only: [:destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :movie
  belongs_to :list
  validates :comment, length: { minimum: 6 }
  validates :list, uniqueness: { scope: :movie }
end

app/models/list.rb
class List < ApplicationRecord
  validates :name, presence: true
  validates :name, uniqueness: true
  has_many :bookmarks, dependent: :destroy
  has_many :movies, through: :bookmarks
  has_many :reviews
  has_one_attached :photo
end

app/models/movie.rb
class Movie < ApplicationRecord
  validates :title, presence: true
  validates :title, uniqueness: true
  validates :overview, presence: true
  has_many :bookmarks
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :list
  validates :comment, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  def index
    @bookmarks = Bookmark.all
  end

  def new
    @list = List.find(params[:list_id])
    @bookmark = Bookmark.new
    @bookmark.list = @list
  end

  def create
    @bookmark = Bookmark.new(bookmark_params)
    @list = List.find(params[:list_id])
    @bookmark.list = @list
    if @bookmark.save
      redirect_to list_path(@list)
    else
      render :new
    end
  end

  def destroy
    @bookmark = Bookmark.find(params[:id])
    @bookmark.destroy
    redirect_to list_path(@bookmark.list)
  end

  # def show
  #   @bookmark = Bookmark.find(params[:id])
  # end



  private

  def bookmark_params
    params.require(:bookmark).permit(:comment, :movie_id, :list)
  end

end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  def index
    @lists = List.all
  end

  def show
    @list = List.find(params[:id])
  end

  def new
    @list = List.new
  end

  def create
    @list = List.new(list_params)
    @list.save
    redirect_to list_path(@list)
  end

  private

  def list_params
    params.require(:list).permit(:name, :photo)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/bookmarks/new.html.erb
<%= simple_form_for [@list, @bookmark] do |f| %>
  <%= f.input :comment %>
  <%= f.association :movie %>
  <%= f.button :submit %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWatchList</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/lists/_form.html.erb
<%= simple_form_for(list) do |f| %>
  <%= f.input :name %>
  <%= f.input :photo, as: :file %>
  <%= f.submit %>
<% end %>

app/views/lists/all.html.erb
<h1>Lists</h1>
<ul>
<% @lists.each do |list| %>
<li><%= list.name %></li>
<% end %>
</ul>

app/views/lists/index.html.erb
<h1>Lists</h1>
<ul>
<% @lists.each do |list| %>
<li><%= cl_image_tag list.photo.key, height: 300, width: 400, crop: :fill %><%= link_to list.name, list_path(list) %></li>
<% end %>
</ul>
<%= link_to 'Add list', new_list_path  %>

app/views/lists/new.html.erb
<%= render "form", list: @list %>

app/views/lists/show.html.erb
<h1>List details for: <%= @list.name %></h1>
<%= cl_image_tag @list.photo.key, height: 300, width: 400, crop: :fill %>
<ul class="list-group">
  <% @list.bookmarks.each do |bookmark| %>
    <li class="list-group-item">
      <%= image_tag bookmark.movie.poster_url, style: 'width:200px' %>
      <%= bookmark.movie.title %> -
      <%= bookmark.comment %> -
      <%= link_to 'Delete',
          bookmark_path(bookmark),
          method: :delete,
          data: { confirm: "Are you sure?" } %>
    </li>
  <% end %>
</ul>
<%= link_to 'Add movie', new_list_bookmark_path(@list) %>
<%= link_to 'Back', lists_path  %>